### ISSUE TITLE
parser format improvements

### ISSUE THREAD

**Issue by brianleroux** [architect/parser#10]
float:

```
@floats
39239392.32232332
2323.323232
```

strings with whitespace:

```
@nom
my-name "my string value"
```

escape comment hash token:

```
@invoices
invoice-\#01 
```

**Comment by mikemaccana** [comment]
Just a quick thought that you could not maintain a parser and switch to JSON-only or .desktop only - maintaining a custom file format is hard work!

**Comment by brianleroux** [comment]
Is 52 commits a lot of work? ¯¯\_(ツ)_/¯¯ 

(we support arc.json fwiw!)

**Comment by mikemaccana** [comment]
Sure `arc.json` exists - suggesting you switch to it and abandon this. 52 commits is a few commits indeed, and there'll be more work in future t support the custom format. Totally up to you if you want to do that, just thinking dumping the custom format might save you (and potentially users) some time.

**Comment by brianleroux** [comment]
All formats are "custom" and the time saving argument isn't really substantive (to me) given those 52 commits are spread over three years. It was not a lot of work nor has it been much to maintain. 

Though it does require explaining which is a form of work! I feel the format solves the problems of JSON and YAML very well which makes it a nice default while still retaining the capability of YAML and JSON if you find comments and flat syntax free structure too easy to read and write. ;)

**Comment by mikemaccana** [comment]
> Though it does require explaining which is a form of work!

Yep. 

> I feel the format solves the problems of JSON and YAML very well which makes it a nice default while still retaining the capability of YAML and JSON 

FDO (.desktop) is really similar.

**Comment by mikemaccana** [comment]
PS sorry if this is hijacking the thread, that wasn't my intention.

**Comment by brianleroux** [comment]
no problem! its an issue for sure. mostly one of perception imo but that still counts.
