### ISSUE TITLE
Parser 2.0 not returning data from some pragmas

### ISSUE THREAD

**Issue by ryanblock** [architect/parser#33]
**Describe the issue**
Tried implementing parser 2.0 and it was not returning some values from an arc file. I spent a few minutes trying to figure out how it works but I wasn't making much progress.

**Steps to reproduce**
- Parse the following Arc file:
```
@app
mockapp

@events
ping

@queues
pong

@http
get /

@tables
accounts
  accountID *String

@indexes
accounts
  email *String
```

With parser 1.x you'll get the following data back (represented here as JSON):
```json
{
  "app": ["mockapp"],
  "events": ["ping"],
  "queues": ["pong"],
  "http": [
    ["get", "/"]
  ],
  "tables": [
    {
      "accounts": {
        "accountID": "*String"
      }
    }
  ],
  "indexes": [
    {
      "accounts": {
        "email": "*String"
      }
    }
  ]
}
```

With parser 2.0 you'll get this:
```json
{
  "app": ["mockapp"],
  "events": ["ping"],
  "queues": ["pong"],
  "http": [
    ["get", "/"]
  ],
  "tables": [
    {
      "accounts": {
        "accountID": "*String"
      }
    }
  ]
}
```

Notice how `@indexes` is missing. For now I'll pull parser 2.0 out of use in the upcoming release of Arc, as it's breaking Sandbox.

**Comment by brianleroux** [comment]
yikessssss! thx for catching that
