### ISSUE TITLE
arc parsing can't handle db keys with octothorpe

### ISSUE THREAD

**Issue by juliedavila** [architect/parser#34]
**Describe the issue**
If I want my dynamo sort key to contain `#` characters, it doesn't work. It does work with YAML parsing. I did try to escape them via `\#` but it seems that is not recognized and the behavior is the same.

**Steps to reproduce**
```
@tables
myTable
  id *String
  thing1#thing2#thing3 **String
```

**Expected behavior**
I would expect for those not to be treated as comments

The traceback is 
```
/Users/jdavila/.nvm/versions/node/v10.16.3/lib/node_modules/@architect/architect/node_modules/@architect/package/src/visitors/tables/get-key-type.js:25
    throw Error('Unknown key type.')
    ^
```

**Comment by brianleroux** [comment]
eh there, super sorry this went for so long, new version (5.x) fixes this issue and should be officially part of the project in a week or so; can see the new behavior here

https://runkit.com/brianleroux/61412589e491ea00082d3ba3
